# GitHub Copilot Setup Steps
# Pre-installs dependencies and generates code before Copilot creates PRs
# Documentation: https://docs.github.com/en/copilot/customizing-copilot/adding-custom-instructions-for-github-copilot

name: mjrwtf-copilot-setup
description: Setup steps for mjr.wtf URL shortener development environment

steps:
  # Step 1: Verify Go version
  - name: Check Go version
    run: |
      GOV=$(go version)
      echo "$GOV"
      if ! echo "$GOV" | grep -q "go1.24"; then
        echo "Warning: Go 1.24.2+ recommended"
      fi

  # Step 2: Install Go dependencies
  - name: Download Go dependencies
    run: |
      go mod download
      go mod verify
    timeout: 120

  # Step 3: Install sqlc (CRITICAL)
  - name: Install sqlc
    run: |
      if ! command -v sqlc >/dev/null 2>&1; then
        go install github.com/sqlc-dev/sqlc/cmd/sqlc@v1.30.0
      fi
      sqlc version
    timeout: 60

  # Step 4: Generate sqlc code (CRITICAL - required before compilation)
  - name: Generate sqlc code
    run: sqlc generate
    timeout: 10
    description: |
      Generates type-safe database code in internal/adapters/repository/sqlc/
      This MUST run before building or testing - compilation will fail without it.

  # Step 5: Install golangci-lint
  - name: Install golangci-lint
    run: |
      if ! command -v golangci-lint >/dev/null 2>&1; then
        curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | \
          sh -s -- -b $(go env GOPATH)/bin v1.56.0
      fi
      golangci-lint version
    timeout: 120

  # Step 6: Build migrate tool (optional; enable with BUILD_MIGRATE=1)
  - name: Build migration tool
    run: |
      if [ "${BUILD_MIGRATE:-0}" != "1" ]; then
        echo "Skipping migrate tool build (set BUILD_MIGRATE=1 to enable)"
      else
        if [ ! -x ./bin/migrate ]; then
          make build-migrate
        else
          echo "bin/migrate already built"
        fi
      fi
    timeout: 30
    description: |
      Builds the migration CLI tool used for database migrations.
      Enable by setting BUILD_MIGRATE=1.

  # Step 7: Set up test environment
  - name: Setup test environment
    run: |
      # Create .env from example if it doesn't exist
      if [ ! -f .env ]; then
        cp .env.example .env
        echo "DATABASE_URL=:memory:" >> .env
      fi
    timeout: 5

  # Step 8: Verify setup by running tests
  - name: Verify setup with tests
    run: make test
    timeout: 30
    description: |
      Runs all tests to verify the environment is correctly configured.
      PostgreSQL tests will skip if database is not available (expected).

validation:
  # Commands that must succeed for setup to be valid
  required:
    - sqlc generate
    - go build ./...
    - make test

  # Optional but recommended
  recommended:
    - make lint
    - make fmt

# Environment variables needed for full functionality
environment:
  - name: DATABASE_URL
    description: Database connection string
    default: ":memory:"
    required: false
  
  - name: CGO_ENABLED
    description: Enable CGO for SQLite support
    default: "1"
    required: true

# Cache these directories for faster subsequent runs
cache:
  - $GOPATH/pkg/mod          # Go module cache
  - $GOPATH/bin              # Installed binaries (sqlc, golangci-lint)
  - bin/                     # Built binaries
  - internal/adapters/repository/sqlc/  # Generated code

# Common issues and solutions
troubleshooting:
  - issue: "undefined: postgresrepo"
    solution: "Run: sqlc generate"
  
  - issue: "bin/migrate: command not found"
    solution: "Run: make build-migrate"
  
  - issue: "golangci-lint errors about undefined packages"
    solution: "These are false positives if tests pass - ignore them"

# Estimated setup time
estimated_duration: 180  # seconds (3 minutes)
