# golangci-lint configuration
# Note: typecheck linter disabled due to false positives with external package imports
# The code compiles correctly but golangci-lint's typecheck has issues recognizing
# imports from goose, chi, sqlite3, geoip2, and sqlc-generated packages

run:
  timeout: 5m
  tests: true
  skip-dirs:
    - internal/adapters/repository/sqlc  # Skip sqlc-generated code

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
  disable:
    - typecheck  # Disabled due to false positives

linters-settings:
  errcheck:
    check-type-assertions: true
  govet:
    check-shadowing: true
  gofmt:
    simplify: true
