// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqliterepo

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.createURLStmt, err = db.PrepareContext(ctx, createURL); err != nil {
		return nil, fmt.Errorf("error preparing query CreateURL: %w", err)
	}
	if q.deleteURLByShortCodeStmt, err = db.PrepareContext(ctx, deleteURLByShortCode); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteURLByShortCode: %w", err)
	}
	if q.findURLByShortCodeStmt, err = db.PrepareContext(ctx, findURLByShortCode); err != nil {
		return nil, fmt.Errorf("error preparing query FindURLByShortCode: %w", err)
	}
	if q.getClicksByCountryStmt, err = db.PrepareContext(ctx, getClicksByCountry); err != nil {
		return nil, fmt.Errorf("error preparing query GetClicksByCountry: %w", err)
	}
	if q.getClicksByCountryInTimeRangeStmt, err = db.PrepareContext(ctx, getClicksByCountryInTimeRange); err != nil {
		return nil, fmt.Errorf("error preparing query GetClicksByCountryInTimeRange: %w", err)
	}
	if q.getClicksByDateStmt, err = db.PrepareContext(ctx, getClicksByDate); err != nil {
		return nil, fmt.Errorf("error preparing query GetClicksByDate: %w", err)
	}
	if q.getClicksByReferrerStmt, err = db.PrepareContext(ctx, getClicksByReferrer); err != nil {
		return nil, fmt.Errorf("error preparing query GetClicksByReferrer: %w", err)
	}
	if q.getClicksByReferrerInTimeRangeStmt, err = db.PrepareContext(ctx, getClicksByReferrerInTimeRange); err != nil {
		return nil, fmt.Errorf("error preparing query GetClicksByReferrerInTimeRange: %w", err)
	}
	if q.getTotalClickCountStmt, err = db.PrepareContext(ctx, getTotalClickCount); err != nil {
		return nil, fmt.Errorf("error preparing query GetTotalClickCount: %w", err)
	}
	if q.getTotalClickCountInTimeRangeStmt, err = db.PrepareContext(ctx, getTotalClickCountInTimeRange); err != nil {
		return nil, fmt.Errorf("error preparing query GetTotalClickCountInTimeRange: %w", err)
	}
	if q.listURLsStmt, err = db.PrepareContext(ctx, listURLs); err != nil {
		return nil, fmt.Errorf("error preparing query ListURLs: %w", err)
	}
	if q.listURLsByCreatedByAndTimeRangeStmt, err = db.PrepareContext(ctx, listURLsByCreatedByAndTimeRange); err != nil {
		return nil, fmt.Errorf("error preparing query ListURLsByCreatedByAndTimeRange: %w", err)
	}
	if q.recordClickStmt, err = db.PrepareContext(ctx, recordClick); err != nil {
		return nil, fmt.Errorf("error preparing query RecordClick: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.createURLStmt != nil {
		if cerr := q.createURLStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createURLStmt: %w", cerr)
		}
	}
	if q.deleteURLByShortCodeStmt != nil {
		if cerr := q.deleteURLByShortCodeStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteURLByShortCodeStmt: %w", cerr)
		}
	}
	if q.findURLByShortCodeStmt != nil {
		if cerr := q.findURLByShortCodeStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing findURLByShortCodeStmt: %w", cerr)
		}
	}
	if q.getClicksByCountryStmt != nil {
		if cerr := q.getClicksByCountryStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getClicksByCountryStmt: %w", cerr)
		}
	}
	if q.getClicksByCountryInTimeRangeStmt != nil {
		if cerr := q.getClicksByCountryInTimeRangeStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getClicksByCountryInTimeRangeStmt: %w", cerr)
		}
	}
	if q.getClicksByDateStmt != nil {
		if cerr := q.getClicksByDateStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getClicksByDateStmt: %w", cerr)
		}
	}
	if q.getClicksByReferrerStmt != nil {
		if cerr := q.getClicksByReferrerStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getClicksByReferrerStmt: %w", cerr)
		}
	}
	if q.getClicksByReferrerInTimeRangeStmt != nil {
		if cerr := q.getClicksByReferrerInTimeRangeStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getClicksByReferrerInTimeRangeStmt: %w", cerr)
		}
	}
	if q.getTotalClickCountStmt != nil {
		if cerr := q.getTotalClickCountStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getTotalClickCountStmt: %w", cerr)
		}
	}
	if q.getTotalClickCountInTimeRangeStmt != nil {
		if cerr := q.getTotalClickCountInTimeRangeStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getTotalClickCountInTimeRangeStmt: %w", cerr)
		}
	}
	if q.listURLsStmt != nil {
		if cerr := q.listURLsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listURLsStmt: %w", cerr)
		}
	}
	if q.listURLsByCreatedByAndTimeRangeStmt != nil {
		if cerr := q.listURLsByCreatedByAndTimeRangeStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listURLsByCreatedByAndTimeRangeStmt: %w", cerr)
		}
	}
	if q.recordClickStmt != nil {
		if cerr := q.recordClickStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing recordClickStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                                  DBTX
	tx                                  *sql.Tx
	createURLStmt                       *sql.Stmt
	deleteURLByShortCodeStmt            *sql.Stmt
	findURLByShortCodeStmt              *sql.Stmt
	getClicksByCountryStmt              *sql.Stmt
	getClicksByCountryInTimeRangeStmt   *sql.Stmt
	getClicksByDateStmt                 *sql.Stmt
	getClicksByReferrerStmt             *sql.Stmt
	getClicksByReferrerInTimeRangeStmt  *sql.Stmt
	getTotalClickCountStmt              *sql.Stmt
	getTotalClickCountInTimeRangeStmt   *sql.Stmt
	listURLsStmt                        *sql.Stmt
	listURLsByCreatedByAndTimeRangeStmt *sql.Stmt
	recordClickStmt                     *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                                  tx,
		tx:                                  tx,
		createURLStmt:                       q.createURLStmt,
		deleteURLByShortCodeStmt:            q.deleteURLByShortCodeStmt,
		findURLByShortCodeStmt:              q.findURLByShortCodeStmt,
		getClicksByCountryStmt:              q.getClicksByCountryStmt,
		getClicksByCountryInTimeRangeStmt:   q.getClicksByCountryInTimeRangeStmt,
		getClicksByDateStmt:                 q.getClicksByDateStmt,
		getClicksByReferrerStmt:             q.getClicksByReferrerStmt,
		getClicksByReferrerInTimeRangeStmt:  q.getClicksByReferrerInTimeRangeStmt,
		getTotalClickCountStmt:              q.getTotalClickCountStmt,
		getTotalClickCountInTimeRangeStmt:   q.getTotalClickCountInTimeRangeStmt,
		listURLsStmt:                        q.listURLsStmt,
		listURLsByCreatedByAndTimeRangeStmt: q.listURLsByCreatedByAndTimeRangeStmt,
		recordClickStmt:                     q.recordClickStmt,
	}
}
