// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqliterepo

import (
	"time"
)

type Click struct {
	ID             int64     `json:"id"`
	UrlID          int64     `json:"url_id"`
	ClickedAt      time.Time `json:"clicked_at"`
	Referrer       *string   `json:"referrer"`
	Country        *string   `json:"country"`
	UserAgent      *string   `json:"user_agent"`
	ReferrerDomain *string   `json:"referrer_domain"`
}

type Url struct {
	ID          int64     `json:"id"`
	ShortCode   string    `json:"short_code"`
	OriginalUrl string    `json:"original_url"`
	CreatedAt   time.Time `json:"created_at"`
	CreatedBy   string    `json:"created_by"`
}

type UrlStatus struct {
	UrlID            int64      `json:"url_id"`
	LastCheckedAt    *time.Time `json:"last_checked_at"`
	LastStatusCode   *int64     `json:"last_status_code"`
	GoneAt           *time.Time `json:"gone_at"`
	ArchiveUrl       *string    `json:"archive_url"`
	ArchiveCheckedAt *time.Time `json:"archive_checked_at"`
}
