// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqliterepo

import (
	"time"
)

type Click struct {
	ID        int64     `json:"id"`
	UrlID     int64     `json:"url_id"`
	ClickedAt time.Time `json:"clicked_at"`
	Referrer  *string   `json:"referrer"`
	Country   *string   `json:"country"`
	UserAgent *string   `json:"user_agent"`
}

type Session struct {
	ID             string    `json:"id"`
	UserID         string    `json:"user_id"`
	CreatedAt      time.Time `json:"created_at"`
	ExpiresAt      time.Time `json:"expires_at"`
	LastActivityAt time.Time `json:"last_activity_at"`
	IpAddress      *string   `json:"ip_address"`
	UserAgent      *string   `json:"user_agent"`
}

type Url struct {
	ID          int64     `json:"id"`
	ShortCode   string    `json:"short_code"`
	OriginalUrl string    `json:"original_url"`
	CreatedAt   time.Time `json:"created_at"`
	CreatedBy   string    `json:"created_by"`
}
