// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqliterepo

import (
	"context"
)

type Querier interface {
	CountURLs(ctx context.Context) (int64, error)
	CountURLsByCreatedBy(ctx context.Context, createdBy string) (int64, error)
	// ============================================================================
	// URL Queries
	// ============================================================================
	CreateURL(ctx context.Context, arg CreateURLParams) (Url, error)
	DeleteURLByShortCode(ctx context.Context, shortCode string) error
	FindURLByShortCode(ctx context.Context, shortCode string) (Url, error)
	GetClicksByCountry(ctx context.Context, urlID int64) ([]GetClicksByCountryRow, error)
	GetClicksByCountryInTimeRange(ctx context.Context, arg GetClicksByCountryInTimeRangeParams) ([]GetClicksByCountryInTimeRangeRow, error)
	GetClicksByDate(ctx context.Context, urlID int64) ([]GetClicksByDateRow, error)
	GetClicksByReferrer(ctx context.Context, urlID int64) ([]GetClicksByReferrerRow, error)
	GetClicksByReferrerInTimeRange(ctx context.Context, arg GetClicksByReferrerInTimeRangeParams) ([]GetClicksByReferrerInTimeRangeRow, error)
	GetTotalClickCount(ctx context.Context, urlID int64) (int64, error)
	GetTotalClickCountInTimeRange(ctx context.Context, arg GetTotalClickCountInTimeRangeParams) (int64, error)
	ListAllURLs(ctx context.Context, arg ListAllURLsParams) ([]Url, error)
	ListURLs(ctx context.Context, arg ListURLsParams) ([]Url, error)
	ListURLsByCreatedByAndTimeRange(ctx context.Context, arg ListURLsByCreatedByAndTimeRangeParams) ([]Url, error)
	// ============================================================================
	// Click Queries
	// ============================================================================
	RecordClick(ctx context.Context, arg RecordClickParams) (RecordClickRow, error)
}

var _ Querier = (*Queries)(nil)
