// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package postgresrepo

import (
	"database/sql"
	"time"
)

type Click struct {
	ID        int32          `json:"id"`
	UrlID     int32          `json:"url_id"`
	ClickedAt time.Time      `json:"clicked_at"`
	Referrer  sql.NullString `json:"referrer"`
	Country   sql.NullString `json:"country"`
	UserAgent sql.NullString `json:"user_agent"`
}

type Url struct {
	ID          int32     `json:"id"`
	ShortCode   string    `json:"short_code"`
	OriginalUrl string    `json:"original_url"`
	CreatedAt   time.Time `json:"created_at"`
	CreatedBy   string    `json:"created_by"`
}
