// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package postgresrepo

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Click struct {
	ID        int32          `json:"id"`
	UrlID     int32          `json:"url_id"`
	ClickedAt time.Time      `json:"clicked_at"`
	Referrer  sql.NullString `json:"referrer"`
	Country   sql.NullString `json:"country"`
	UserAgent sql.NullString `json:"user_agent"`
}

type Session struct {
	ID             uuid.UUID      `json:"id"`
	UserID         string         `json:"user_id"`
	CreatedAt      time.Time      `json:"created_at"`
	ExpiresAt      time.Time      `json:"expires_at"`
	LastActivityAt time.Time      `json:"last_activity_at"`
	IpAddress      sql.NullString `json:"ip_address"`
	UserAgent      sql.NullString `json:"user_agent"`
}

type Url struct {
	ID          int32     `json:"id"`
	ShortCode   string    `json:"short_code"`
	OriginalUrl string    `json:"original_url"`
	CreatedAt   time.Time `json:"created_at"`
	CreatedBy   string    `json:"created_by"`
}
