// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package postgresrepo

import (
	"context"
	"time"

	"github.com/google/uuid"
)

type Querier interface {
	// ============================================================================
	// Session Queries
	// ============================================================================
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	// ============================================================================
	// URL Queries
	// ============================================================================
	CreateURL(ctx context.Context, arg CreateURLParams) (Url, error)
	DeleteExpiredSessions(ctx context.Context) (int64, error)
	DeleteIdleSessions(ctx context.Context, lastActivityAt time.Time) (int64, error)
	DeleteSession(ctx context.Context, id uuid.UUID) error
	DeleteSessionsByUserID(ctx context.Context, userID string) error
	DeleteURLByShortCode(ctx context.Context, shortCode string) error
	FindURLByShortCode(ctx context.Context, shortCode string) (Url, error)
	GetClicksByCountry(ctx context.Context, urlID int32) ([]GetClicksByCountryRow, error)
	GetClicksByCountryInTimeRange(ctx context.Context, arg GetClicksByCountryInTimeRangeParams) ([]GetClicksByCountryInTimeRangeRow, error)
	GetClicksByDate(ctx context.Context, urlID int32) ([]GetClicksByDateRow, error)
	GetClicksByReferrer(ctx context.Context, urlID int32) ([]GetClicksByReferrerRow, error)
	GetClicksByReferrerInTimeRange(ctx context.Context, arg GetClicksByReferrerInTimeRangeParams) ([]GetClicksByReferrerInTimeRangeRow, error)
	GetSessionByID(ctx context.Context, id uuid.UUID) (Session, error)
	GetTotalClickCount(ctx context.Context, urlID int32) (int64, error)
	GetTotalClickCountInTimeRange(ctx context.Context, arg GetTotalClickCountInTimeRangeParams) (int64, error)
	ListSessionsByUserID(ctx context.Context, userID string) ([]Session, error)
	ListURLs(ctx context.Context, arg ListURLsParams) ([]Url, error)
	ListURLsByCreatedByAndTimeRange(ctx context.Context, arg ListURLsByCreatedByAndTimeRangeParams) ([]Url, error)
	// ============================================================================
	// Click Queries
	// ============================================================================
	RecordClick(ctx context.Context, arg RecordClickParams) (Click, error)
	UpdateSessionActivity(ctx context.Context, arg UpdateSessionActivityParams) error
}

var _ Querier = (*Queries)(nil)
