name: Docker Image Publish

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  docker-publish:
    permissions:
      contents: read
      packages: write
    uses: matt-riley/matt-riley-ci/.github/workflows/docker-ghcr-publish.yml@cb986078a5bd4775e5fb05348f3618e41fedf4de # v4
    with:
      tag-name: ${{ github.ref_type == 'tag' && github.ref_name || '' }}
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
